config/routes.rb
# encoding: utf-8
Kaffkass::Application.routes.draw do
  # Authlogic
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users do
    resources :holidays, :only => [:index, :new, :create, :destroy]
  end
  resource :user, :as => 'account'

  match 'signup' => 'users#new', :as => :signup

  # E-Mail Aktivierung
  match '/activate/:activation_code', :controller => 'activations', :action => 'create' , :as => :activate

  # Anwendungsrouten

  resources :coffee_boxes do
    resources :model_of_consumptions
    resources :consumptions, :only => [:index,:update]
    resources :bills, :only => [:index]
    resources :expenses
  end

  # An-Abmeldung zu Kaffeerunden
  match 'coffee_boxes/:id/new_participate' => 'coffee_boxes#new_participate', :as => :new_participate
  match 'coffee_boxes/:id/participate' => 'coffee_boxes#participate', :as => :participate
  match 'coffee_boxes/:id/unparticipate' => 'coffee_boxes#unparticipate', :as => :unparticipate

  # Kaffeerunden, an denen der angemeldete User teilnimmt
  match 'my_coffee_boxes' => 'coffee_boxes#my_coffee_boxes', :as => :my_coffee_boxes

  # Route für Monatsabschluss
  match '/coffee_boxes/:coffee_box_id/close_month' => 'consumptions#close_month', :as => :close_month_coffee_box

  # Route für JSON-Abfrage der Konsum-Statistik für eine Kaffeerunde
  get '/coffee_boxes/:coffee_box_id/consume_chart/:year/:month' => 'statistics#consume_chart', :as => :coffee_box_consume_chart

  # Route für Markieren von Rechnungen als bezahlt
  match '/coffee_boxes/:coffee_box_id/mark_as_paid/:id' => 'bills#mark_as_paid', :as => :mark_as_paid

  # Root wird auf Home#home geroutet
  root :to => 'home#home'
end

app/models/notifier.rb
# encoding: utf-8
class Notifier < ActionMailer::Base

  def activation_instructions(user)
    @user = user
    mail = @user.email
    mail(to: mail, from: 'no-reply@kaffkass.com',
         subject: "KaffKass Accountaktivierung")
  end

  def welcome(user)
    @user = user
    mail = @user.email
    mail(to: mail, from: 'no-reply@kaffkass.com',
         subject: "Willkommen bei KaffKass!")
  end

  def bill(bill, user)
    @user = user
    mail = @user.email
    @bill = bill
    mail(to: mail, from: 'no-reply@kaffkass.com',
         subject: "KaffKass - Rechnung für #{bill.date}")
  end

end

app/views/notifier/activation_instructions.erb
<html>
<p>

Vielen Dank für Ihre Registrierung! Klicken sie auf folgende URL, um Ihren Account zu aktivieren: <br/> <br/>

<a href="http://localhost:3000<%= @account_activation_path %><%= activate_path(@user.persistence_token) %>">http://localhost:3000<%= @account_activation_path %><%= activate_path(@user.persistence_token) %></a> <br/> <br/>

Sollte der Link nicht funktionieren, versuchen Sie den Link zu kopieren und in die Adresszeile Ihres Browser einzufügen.
</p>
</html>

app/views/notifier/bill.erb
Monat: <%= @bill.date %>
Betrag: <%= number_to_currency @bill.value, :unit => "Euro", :separator => ",", :precision => 2 %>

app/views/notifier/welcome.erb
Willkommen bei KaffKass! Ihr Account wurde aktiviert!