config/routes.rb
# encoding: utf-8
Kaffkass::Application.routes.draw do
  # Authlogic
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users do
    resources :holidays, :only => [:index, :new, :create, :destroy]
  end
  resource :user, :as => 'account'

  match 'signup' => 'users#new', :as => :signup

  # E-Mail Aktivierung
  match '/activate/:activation_code', :controller => 'activations', :action => 'create' , :as => :activate

  # Anwendungsrouten

  resources :coffee_boxes do
    resources :model_of_consumptions
    resources :consumptions, :only => [:index,:update]
    resources :bills, :only => [:index]
    resources :expenses
  end

  # An-Abmeldung zu Kaffeerunden
  match 'coffee_boxes/:id/new_participate' => 'coffee_boxes#new_participate', :as => :new_participate
  match 'coffee_boxes/:id/participate' => 'coffee_boxes#participate', :as => :participate
  match 'coffee_boxes/:id/unparticipate' => 'coffee_boxes#unparticipate', :as => :unparticipate

  # Kaffeerunden, an denen der angemeldete User teilnimmt
  match 'my_coffee_boxes' => 'coffee_boxes#my_coffee_boxes', :as => :my_coffee_boxes

  # Route für Monatsabschluss
  match '/coffee_boxes/:coffee_box_id/close_month' => 'consumptions#close_month', :as => :close_month_coffee_box

  # Route für JSON-Abfrage der Konsum-Statistik für eine Kaffeerunde
  get '/coffee_boxes/:coffee_box_id/consume_chart/:year/:month' => 'statistics#consume_chart', :as => :coffee_box_consume_chart

  # Route für Markieren von Rechnungen als bezahlt
  match '/coffee_boxes/:coffee_box_id/mark_as_paid/:id' => 'bills#mark_as_paid', :as => :mark_as_paid

  # Root wird auf Home#home geroutet
  root :to => 'home#home'
end

app/models/model_of_consumption.rb
class ModelOfConsumption < ActiveRecord::Base
  belongs_to :coffee_box
  belongs_to :user

  validates :mo, :tue, :wed, :th, :fr, :sa, :su, :numericality => {:greater_than_or_equal_to => 0}
  validates :coffee_box_id, :presence => true
  validates :user_id, :presence => true


  # @param [ModelOfConsumption] consumption_model
  def self.update_model(consumption_model, params)
    # Änderungen speichern
    if consumption_model.update_attributes(params)
      # Alle Consumptions updaten, deren FlagTouched nicht gesetzt ist und für den Monat noch keine Bill vorhanden ist
      all_consumptions = Consumption.where(:user_id => consumption_model.user_id).all

      # Aussortieren der Tage, die schon abgerechnet wurden
      non_cleared_consumptions = Array.new
      all_consumptions.each do |c|
        if not c.is_cleared?
          non_cleared_consumptions.append(c)
        end
      end

      non_cleared_consumptions.each do |c|
        if not c.flag_touched?
          ## Tag wurde noch nicht manuell bearbeitet
          # -> Tag updaten
          c.number_of_cups = consumption_model.get_cups_for_weekday(c.day)
          c.save
        end
      end
      return true
    else
      return false
    end
  end

  # Gibt die Anzahl der Tassen zurück, die laut Konsummodell an diesem Tag konsumiert werden.
  def get_cups_for_weekday(date)
    if date.wday == 1
      self.mo
    elsif date.wday == 2
      self.tue
    elsif date.wday == 3
      self.wed
    elsif date.wday == 4
      self.th
    elsif date.wday == 5
      self.fr
    elsif date.wday == 6
      self.sa
    elsif date.wday == 0
      self.su
    else
       0
    end
  end
end

app/controllers/model_of_consumptions_controller.rb
# encoding: utf-8
class ModelOfConsumptionsController < ApplicationController
  before_filter :require_user

  def new
    @coffee_box = CoffeeBox.find(params[:coffee_box_id])
    @model_of_consumption = current_user.model_of_consumptions.build
  end

  def create
    @coffee_box = CoffeeBox.find(params[:coffee_box_id])
    if params[:no_consumption_model]
      redirect_to coffee_boxes_path, notice: "Kein Konsummodell hinterlegt."
    else
      @model_of_consumption = current_user.model_of_consumptions.build(params[:model_of_consumption])
      @model_of_consumption.coffee_box = CoffeeBox.find(params[:coffee_box_id])
      if @model_of_consumption.save
        redirect_to coffee_boxes_path, notice: "Konsummodell erfolgreich hinterlegt."
      else
        render "new"
      end
    end
  end

  def destroy
    @coffee_box = CoffeeBox.find(params[:coffee_box_id])
    @model_of_consumption = ModelOfConsumption.find(params[:id])
    @model_of_consumption.destroy
    redirect_to coffee_box_path(@coffee_box), notice: "Konsummodell gelöscht."
  end

  def show
    @coffee_box = CoffeeBox.find(params[:coffee_box_id])
    @model_of_consumption = ModelOfConsumption.find(params[:id])
  end

  def edit
    @model_of_consumption = ModelOfConsumption.find(params[:id])
    @coffee_box = CoffeeBox.find(params[:coffee_box_id])
  end

  def update
    @model_of_consumption = ModelOfConsumption.find(params[:id])

    if ModelOfConsumption.update_model(@model_of_consumption, params[:model_of_consumption])
      redirect_to coffee_boxes_path, notice: "Update des Konsummodells erfolgreich."
    else
      render "edit"
    end
  end

end

app/views/model_of_consumptions/edit.html.erb
<%= render "shared/error_messages", :target => @model_of_consumption %>

<%= form_for [@coffee_box, @model_of_consumption] do |f| %>
    <%= field_set_tag "Konsummodell bearbeiten" do %>
        <table id="consumption_table">
          <thead>
          <tr>
            <th>Mo</th>
            <th>Di</th>
            <th>Mi</th>
            <th>Do</th>
            <th>Fr</th>
            <th>Sa</th>
            <th>So</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td><%= f.number_field :mo, :min => 0, :step => 1 %></td>
            <td><%= f.number_field :tue, :min => 0, :step => 1 %></td>
            <td><%= f.number_field :wed, :min => 0, :step => 1 %></td>
            <td><%= f.number_field :th, :min => 0, :step => 1 %></td>
            <td><%= f.number_field :fr, :min => 0, :step => 1 %></td>
            <td><%= f.number_field :sa, :min => 0, :step => 1 %></td>
            <td><%= f.number_field :su, :min => 0, :step => 1 %></td>
            <td>Anzahl Tassen</td>
          </tr>
          </tbody>
        </table>
        <p><%= f.submit %></p>
    <% end %>
<% end %>

app/views/model_of_consumptions/new.html.erb
<%= render "shared/error_messages", :target => @model_of_consumption %>

<p><%= t "text.consumption_model" %></p><br/>

<%= form_for [@coffee_box, @model_of_consumption] do |f| %>
    <%= field_set_tag "Konsummodell hinterlegen" do %>
        <table id="consumption_table">
          <thead>
          <tr>
            <th>Mo</th>
            <th>Di</th>
            <th>Mi</th>
            <th>Do</th>
            <th>Fr</th>
            <th>Sa</th>
            <th>So</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td><%= f.number_field :mo, :min => 0, :step => 1 %></td>
            <td><%= f.number_field :tue, :min => 0, :step => 1 %></td>
            <td><%= f.number_field :wed, :min => 0, :step => 1 %></td>
            <td><%= f.number_field :th, :min => 0, :step => 1 %></td>
            <td><%= f.number_field :fr, :min => 0, :step => 1 %></td>
            <td><%= f.number_field :sa, :min => 0, :step => 1 %></td>
            <td><%= f.number_field :su, :min => 0, :step => 1 %></td>
            <td>Anzahl Tassen</td>
          </tr>
          </tbody>
        </table>
        <div>
          <%= check_box_tag :no_consumption_model %>
          <%= label_tag :no_consumption_model, "Kein Konsummodell", :class => "checkbox inline" %>
          <div class="description"><%= t("text.no_consumption_model")  %></div>
        </div>
        <p id="no_consumption_model">
        </p>
        <p><%= f.submit %></p>
    <% end %>
<% end %>

app/views/model_of_consumptions/show.html.erb
<% @title = "Konsummodell anzeigen" %>

<h2>Konsummodell</h2>
<p>Kaffeerunde: <%= @coffee_box.location %>, <%= l @coffee_box.time, format: :very_short %></p>
<table id="ktable">
  <thead>
  <tr>
    <th>Mo</th>
    <th>Di</th>
    <th>Mi</th>
    <th>Do</th>
    <th>Fr</th>
    <th>Sa</th>
    <th>So</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= @model_of_consumption.mo %></td>
    <td><%= @model_of_consumption.tue %></td>
    <td><%= @model_of_consumption.wed %></td>
    <td><%= @model_of_consumption.th %></td>
    <td><%= @model_of_consumption.fr %></td>
    <td><%= @model_of_consumption.sa %></td>
    <td><%= @model_of_consumption.su %></td>
    <td>Anzahl Tassen</td>
  </tr>
  </tbody>
</table>


<%= link_to "Bearbeiten", edit_coffee_box_model_of_consumption_path(@coffee_box, @model_of_consumption) %>
<%= link_to "Löschen", coffee_box_model_of_consumption_path(@coffee_box, @model_of_consumption), method: :delete%>