config/routes.rb
# encoding: utf-8
Kaffkass::Application.routes.draw do
  # Authlogic
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users do
    resources :holidays, :only => [:index, :new, :create, :destroy]
  end
  resource :user, :as => 'account'

  match 'signup' => 'users#new', :as => :signup

  # E-Mail Aktivierung
  match '/activate/:activation_code', :controller => 'activations', :action => 'create' , :as => :activate

  # Anwendungsrouten

  resources :coffee_boxes do
    resources :model_of_consumptions
    resources :consumptions, :only => [:index,:update]
    resources :bills, :only => [:index]
    resources :expenses
  end

  # An-Abmeldung zu Kaffeerunden
  match 'coffee_boxes/:id/new_participate' => 'coffee_boxes#new_participate', :as => :new_participate
  match 'coffee_boxes/:id/participate' => 'coffee_boxes#participate', :as => :participate
  match 'coffee_boxes/:id/unparticipate' => 'coffee_boxes#unparticipate', :as => :unparticipate

  # Kaffeerunden, an denen der angemeldete User teilnimmt
  match 'my_coffee_boxes' => 'coffee_boxes#my_coffee_boxes', :as => :my_coffee_boxes

  # Route für Monatsabschluss
  match '/coffee_boxes/:coffee_box_id/close_month' => 'consumptions#close_month', :as => :close_month_coffee_box

  # Route für JSON-Abfrage der Konsum-Statistik für eine Kaffeerunde
  get '/coffee_boxes/:coffee_box_id/consume_chart/:year/:month' => 'statistics#consume_chart', :as => :coffee_box_consume_chart

  # Route für Markieren von Rechnungen als bezahlt
  match '/coffee_boxes/:coffee_box_id/mark_as_paid/:id' => 'bills#mark_as_paid', :as => :mark_as_paid

  # Root wird auf Home#home geroutet
  root :to => 'home#home'
end

app/models/user.rb
class User < ActiveRecord::Base

  #Authlogic: defining that this is the model to use for logging in and out
  acts_as_authentic do |c|
  end # block optional
  
  # Validierung
  validates :firstname, :presence => true
  validates :lastname, :presence => true
  validates :email, :presence => true, :uniqueness => true
  validates_format_of :password, :with => /^(?=.*\d)(?=.*([a-z]|[A-Z]))([\x20-\x7E]){4,}$/, :if => :require_password?, :message => "muss mindestens eine Nummer und einen Buchstaben enthalten"

  ## Beziehungen
  # Rechnungen
  has_many :bills
  # Zwischentabelle für Teilnahme an Kaffeerunden
  has_many :participations
  # Direkter Zugriff auf alle Kaffeerunden, an denen der User teilnimmt
  has_many :coffee_boxes, :through => :participations
  # Kaffeerunden, die der User verwaltet
  has_many :administrated_coffee_boxes, :class_name => "CoffeeBox"
  # Kaffeeverbrauch
  has_many(:consumptions)
  # Kaffeeausgaben
  has_many(:expenses)
  # Urlaub
  has_many(:holidays)
  # Konsummodell
  has_many(:model_of_consumptions)


  ## Methoden
  def fullname
    "#{firstname} #{lastname}"
  end

  def fullname_lastname_first
    "#{lastname}, #{firstname}"
  end

  def deliver_activation_instructions!
    reset_persistence_token!
    Notifier.activation_instructions(self).deliver
  end

  def deliver_welcome!
    reset_persistence_token!
    Notifier.welcome(self).deliver
  end

  def deliver_bill!(bill)
    Notifier.bill(bill,self).deliver
  end

  def activate!
    self.active = true
    save
  end

  # Gibt true zurück, wenn der User für die übergebene CoffeeBox angemeldet ist.
  # @param coffee_box CoffeeBox
  def participates?(coffee_box)
    # Kaffeerunden holen
    coffee_boxes = self.coffee_boxes.all
    coffee_boxes.each do |c|
      if c.id == coffee_box.id
        return true
      end
    end
    false
  end

  # Liefert ein Array mit noch nicht bezahlten Bills des Users zurück.
  def get_open_bills
    self.bills.where(is_paid: false)
  end
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController

  # Authorisierung über Cancan
  load_and_authorize_resource

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    # Saving without session maintenance to skip
    # auto-login which can't happen here because
    # the User has not yet been activated
    if @user.save_without_session_maintenance
      @user.deliver_activation_instructions!
      flash[:notice] = "Ihr Account wurde erstellt. Bitte prüfen Sie ihren E-Mail-Eingang!"
      redirect_to root_url
    else
      flash[:notice] = "Beim Erstellen ihres Accounts ist ein Problem aufgetreten."
          render :action => :new
    end

  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account aktualisiert!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end



end

app/views/users/_form.html.erb
<%= render "shared/error_messages", :target => @user %>
<fieldset>
  <legend><%= form.object.new_record? ? "Neues Benutzerkonto" : "Konto bearbeiten" %></legend>
  <p>
    <%= form.label :firstname %><br/>
    <%= form.text_field :firstname %>
  </p>

  <p>
    <%= form.label :lastname %><br/>
    <%= form.text_field :lastname %>
  </p>

  <p>
    <%= form.label :email %><br/>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :password, form.object.new_record? ? nil : "Passwortänderung" %><br/>
    <%= form.password_field :password %>
  </p>

  <p>
    <%= form.label :password_confirmation %><br/>
    <%= form.password_field :password_confirmation %>
  </p>
</fieldset>

app/views/users/edit.html.erb
<%= form_for @user, :url => account_path do |f| %>
    <%= render :partial => "form", :object => f, :locals => { :user => @user } %>
    <%= f.submit %>
<% end %>

<br /><%= link_to "Zurück zum Profil", account_path %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
    <%= render :partial => "form", :object => f, :locals => { :user => @user } %>
    <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<fieldset>
  <legend>Benutzerprofil</legend>
  <div class="info">
    <h3>Hallo, <%= @user.fullname %>!</h3>

    <table id="ktable">
      <thead>
      <tr>
        <th colspan="2">Ihre Daten</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <th>Vorname</th>
        <td><%= @user.firstname %></td>
      </tr>
      <tr>
        <th>Nachname</th>
        <td><%= @user.lastname %></td>
      </tr>
      <tr>
        <th>E-Mail</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>Mitglied seit</th>
        <td><%= l @user.created_at %></td>
      </tr>
      <tr>
        <th>Status</th>
        <td><%= @user.active? ? "Aktiviert" : "Nicht aktiviert" %></td>
      </tr>
      </tbody>
    </table>

    <br/>

    <% if not @user.get_open_bills.empty? %>
        <h3>Offene Rechnungen</h3>
        <table id="ktable">
          <thead>
            <tr>
              <th>Kaffeerunde</th>
              <th>Datum</th>
              <th>Betrag</th>
            </tr>
          </thead>
          <tbody>
            <% @user.get_open_bills.each do |bill| %>
                <tr>
                  <td><%= link_to bill.coffee_box.location, coffee_box_path(bill.coffee_box) %></td>
                  <td><%= l bill.date %></td>
                  <td><%= number_to_currency bill.value %></td>
                </tr>
            <% end %>
          </tbody>
        </table>
    <% end %>

    <br/>

    <p class="button"><a href="#" class="open_close">[+] Sicherheitsinformationen</a></p>

    <div id="security_info">
      <p>
        <b>Login-Anzahl:</b>
        <%= @user.login_count %>
      </p>

      <p>
        <b>Letzte Anfrage:</b>
        <%= l @user.last_request_at, format: :short %>
      </p>


      <p>
        <b>Aktueller Login:</b>
        <%= l @user.current_login_at, format: :short %>
      </p>

      <p>
        <b>Letzte Login IP:</b>
        <%= @user.last_login_ip %>
      </p>

      <p>
        <b>Aktuelle Login IP:</b>
        <%= @user.current_login_ip %>
      </p>
    </div>

  </div>
  <div class="actions right">
    <ul>
      <li>
        <%= link_to "Bearbeiten", edit_account_path %>
      </li>
      <li>
        <%= link_to "Urlaub verwalten", user_holidays_path(current_user) %>
      </li>
    </ul>
  </div>

</fieldset>
