config/routes.rb
# encoding: utf-8
Kaffkass::Application.routes.draw do
  # Authlogic
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users do
    resources :holidays, :only => [:index, :new, :create, :destroy]
  end
  resource :user, :as => 'account'

  match 'signup' => 'users#new', :as => :signup

  # E-Mail Aktivierung
  match '/activate/:activation_code', :controller => 'activations', :action => 'create' , :as => :activate

  # Anwendungsrouten

  resources :coffee_boxes do
    resources :model_of_consumptions
    resources :consumptions, :only => [:index,:update]
    resources :bills, :only => [:index]
    resources :expenses
  end

  # An-Abmeldung zu Kaffeerunden
  match 'coffee_boxes/:id/new_participate' => 'coffee_boxes#new_participate', :as => :new_participate
  match 'coffee_boxes/:id/participate' => 'coffee_boxes#participate', :as => :participate
  match 'coffee_boxes/:id/unparticipate' => 'coffee_boxes#unparticipate', :as => :unparticipate

  # Kaffeerunden, an denen der angemeldete User teilnimmt
  match 'my_coffee_boxes' => 'coffee_boxes#my_coffee_boxes', :as => :my_coffee_boxes

  # Route für Monatsabschluss
  match '/coffee_boxes/:coffee_box_id/close_month' => 'consumptions#close_month', :as => :close_month_coffee_box

  # Route für JSON-Abfrage der Konsum-Statistik für eine Kaffeerunde
  get '/coffee_boxes/:coffee_box_id/consume_chart/:year/:month' => 'statistics#consume_chart', :as => :coffee_box_consume_chart

  # Route für Markieren von Rechnungen als bezahlt
  match '/coffee_boxes/:coffee_box_id/mark_as_paid/:id' => 'bills#mark_as_paid', :as => :mark_as_paid

  # Root wird auf Home#home geroutet
  root :to => 'home#home'
end

app/models/consumption.rb
class Consumption < ActiveRecord::Base
  belongs_to :user
  belongs_to :coffee_box

  # Validierungen
  validates :number_of_cups, :numericality => {:only_integer => true}

  #Legt für einen Monat und User und Kaffee_box alle Consumptions an.
  #Die Konsumptions werden dabei abhängig von einem hinterlgeten Konsummodell und eingetragenem Urlaub vorbefüllt
  #Wird nicht ausgeführt, wenn der Monat vor dem Erstellungsdatum der coffee_box liegt oder die consumption für den Tag bereits existiert
  def self.create_month(date, current_user, coffee_box)
    from = date.beginning_of_month-1
    to = date.end_of_month-1
    tmp = from
    # Wenn für den nächsten Monat bereits ein Preis existiert, dann wurde der akt. Monat schon abgerechnet
    flag_abgerechnet = false
    next_month = date>>1
    if coffee_box.price_of_coffees.where(date: next_month.beginning_of_month .. next_month.end_of_month).exists?
      logger.debug "## Monat #{date} der CoffeeBox #{coffee_box.id} bereits abgeschlossen, alle Consumptions werden disabled."
      flag_abgerechnet = true
    end
    begin
      tmp += 1.day
      if !current_user.consumptions.where(coffee_box_id: coffee_box, day: tmp).exists? && coffee_box.created_at < tmp+1
        @temp_consumption = current_user.consumptions.build
        @temp_consumption.coffee_box=coffee_box
        @temp_consumption.flag_touched= false
        @temp_consumption.day= tmp
        @temp_consumption.flag_disabled= false
        if current_user.model_of_consumptions.where(coffee_box_id: coffee_box).exists?
          # Für die Kaffeerunde existiert ein Konsummodell
          # Anzahl der Tassen vorbelegen
          @model = current_user.model_of_consumptions.where(coffee_box_id: coffee_box).first
          @temp_consumption.number_of_cups = @model.get_cups_for_weekday(tmp)
        else
          @temp_consumption.number_of_cups = 0
        end
        if flag_abgerechnet
          # Monat wurde bereits abgeschlossen, alle Consumptions disablen
          @temp_consumption.flag_disabled = true
        end
        if Holiday.is_holiday tmp, current_user
          # Für den aktuellen Tag ist ein Urlaub hinterlegt
          # Tag als Urlaub markieren, Tassen auf 0 setzen
          @temp_consumption.number_of_cups = 0
          @temp_consumption.flag_holiday = true
        end

        current_user.consumptions << @temp_consumption
      end
      current_user.save
    end while tmp <= to
  end

  # Gibt true zurück, wenn die Consumption schon abgerechnet wurde.
  def is_cleared?
    # Wenn für Monat/User/CoffeeBox schon eine Bill existiert, dann wurde die Consumption schon abgerechnet
    Bill.where(user_id: self.user.id, coffee_box_id: self.coffee_box.id, date: self.day.beginning_of_month..self.day.end_of_month).exists?
  end

end

app/controllers/consumptions_controller.rb
# encoding: utf-8
class ConsumptionsController < ApplicationController

  before_filter :require_user, :only => [:index]


  def index
    #überprüfe ob der User an der Kaffeerunde teilnimmt
    if @current_user.participations.where(coffee_box_id: params[:coffee_box_id]).exists?
      #Aktuelle coffee_box
      @coffee_box = CoffeeBox.find(params[:coffee_box_id])
      #Monat im Kalender setzen oder verändern
      @date = params[:month] ? Date.parse(params[:month]) : Date.today
      #Keinen Monat anzeigen der vor dem erstellungdatum liegt
      if @date.month < @coffee_box.created_at.month && @date.year <= @coffee_box.created_at.year
        @date = Date.today
      end
      #Consumptions für den Monat erzeugen falls nicht vorhanden
      Consumption.create_month(@date, current_user, @coffee_box)
      #Consumptions laden
      @consumptions = current_user.consumptions.where(coffee_box_id: @coffee_box, day: @date.beginning_of_month..@date.end_of_month).all
      respond_to do |format|
        format.html
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to coffee_boxes_path, notice: 'Zugriff verweigert. Sie müssen an der Kaffeerunde teilnehmen.' }
      end
    end
  end


  def edit
    @coffee_box = CoffeeBox.find(params[:coffee_box_id])
    @consumption = current_user.consumptions.find(params[:id])
    authorize! :edit, @consumption, :message => 'Zugriff auf fremden Konsumeintrag verweigert.'
    respond_to do |format|
      format.js
      format.html
    end
  end


  def update
    @consumption = current_user.consumptions.find(params[:id])
    @coffee_box = CoffeeBox.find(params[:coffee_box_id])
    authorize! :edit, @consumption, :message => 'Zugriff auf fremden Konsumeintrag verweigert.'
    @consumption.flag_touched = true
    respond_to do |format|
      if @consumption.update_attributes(params[:consumption])
        format.html { redirect_to coffee_box_consumptions_path, notice: 'Consumption was successfully updated.' }
        format.json { head :ok }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @consumption.errors, status: :unprocessable_entity }
      end
    end
  end


  def close_month
    # Monat der im Kalender ausgewählt ist
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
    # Aktuelle coffee_box
    @coffee_box = CoffeeBox.find(params[:coffee_box_id])
    # Abschließen nur möglich wenn auch ein price besteht
    if @coffee_box.price_of_coffees.where(date: @date.beginning_of_month .. @date.end_of_month).exists?
      Bill.create_bill_for_month(@date, current_user, @coffee_box)
      PriceOfCoffee.create_price_for_next_month(@date, @coffee_box)
    end
    respond_to do |format|
      format.html { redirect_to coffee_box_consumptions_url(month: @date.strftime("%Y/%m")), notice: 'Monat erfolgreich abgeschlossen.' }
      format.json { head :no_content }
    end
  end

end

app/views/consumptions/_calendar.html.erb
<%= calendar_for @consumptions, year: @date.year, month: @date.month , first_day_of_week: 1 do |calendar| %>
    <%= calendar.head('Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag') %>
    <%= calendar.day(:day_method => :day) do |date, consumptions| %>
        <%= date.day %>
        <% for consumption in consumptions %>
                <% if !consumption.flag_disabled && !consumption.flag_holiday %>
                    <div class="numberOfCups">
                      <%= image_tag("cup.png", id: 'cupPng') %>
                      <%= best_in_place consumption, :number_of_cups, path: coffee_box_consumption_path(@coffee_box, consumption), :html_attrs => {:maxlength => 5, :style => "width:1.5em"} %>
                    </div>
                <% elsif consumption.flag_holiday %>
                    <div class="numberOfCupsDisabled">
                      <%= image_tag("sonne.JPG", id: 'sonneJpg')%> <br/>
                      <div id="inner"> <%= consumption.number_of_cups %></div>
                    </div>
                <% else %>
                    <div class="numberOfCupsDisabled">
                      <%= image_tag("cup.png", id: 'cupPng') %> </br>
                      <div id="inner"> <%=  consumption.number_of_cups %> </div>
                    </div>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/consumptions/_selector.html.erb
<h2 id="mont">
  <%= link_to "<", coffee_box_consumptions_path(:month => (@date.beginning_of_month-1).strftime("%Y/%m")), remote: true, :class => "loader" %>
  <%= l @date, format: :month_year %>
  <%= link_to ">", coffee_box_consumptions_path(:month => (@date.end_of_month+1).strftime("%Y/%m")), remote: true, :class => "loader" %>
</h2>
<div id="closeMonth">
  <%
     #Logik ob link angezeigt werden soll
     exists = @coffee_box.price_of_coffees.where(date: @date.beginning_of_month .. @date.end_of_month).exists?
     next_month = @date>>1
     exists_next_mont = @coffee_box.price_of_coffees.where(date:  next_month.beginning_of_month ..  next_month.end_of_month).exists?
     exists_bill = @coffee_box.bills.where(user_id: current_user,date: @date.beginning_of_month .. @date.end_of_month).exists?
  %>
  <%= link_to_if exists && !exists_next_mont && !exists_bill, "Monat abschließen", close_month_coffee_box_path(@coffee_box, :month => @date.strftime("%Y/%m")) %>
</div>

app/views/consumptions/index.html.erb
<fieldset>
  <legend>Tassenverbrauch melden</legend>
  <div id="calendar">
    <div id="selectorField">
      <table> <%= render 'selector' %> </table>
    </div>
    <%= image_tag("loader.gif", id: 'loadGif') %>
    <div id="calendarField">
      <%= render 'calendar' %>
    </div>
  </div>
</fieldset>

app/views/consumptions/index.js.erb
$("#loadGif").hide();
$("#calendarField > table").remove();
$("#calendarField").append("<%= escape_javascript(render(:partial => "calendar"))%>").fadeIn();
$("#selectorField ").children().remove();
$("#selectorField").append("<%= escape_javascript(render(:partial => "selector"))%>").fadeIn();


